version: '3.4'

services:
  cadastropessoa.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    # ports:
    #   - "80"
    #   - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    # image: ${DOCKER_REGISTRY-}cadastropessoaapi
    image: api-pessoa

    build:
      context: .
      dockerfile: back-end/CadastroPessoa.Api/Dockerfile
    networks:
      - pg
    depends_on:
      - postgres_service
    ports:
      - "8090:80"
      - "8091:443"

  person.app:
   image: viniciusmoreiradamatta/app-pessoa
  #  build:
  #    context: .
  #    dockerfile: front-end/crud-pessoa-app/Dockerfile
   depends_on:
     - cadastropessoa.api
   ports:
     - 80:80 
   networks:
      - pg

  postgres_service:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=senha1234
      - POSTGRES_USER=dbUser
      - POSTGRES_DB=CadastroPessoaDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/scripts/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432    
    networks:
      - pg

  postgres_UI:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@email.com
      - PGADMIN_DEFAULT_PASSWORD=172839
    ports:
      - 8080:80
    networks:
      - pg

volumes:
  postgres_data:
    driver: local

networks:
  pg:
    driver: bridge    
